export function handleDiagnosticsPage(request) {
  if (!['GET', 'HEAD'].includes(request.method) || new URL(request.url).pathname.replace(/\/+$/, '') !== '/admin/diagnostics') return null;
  const html = `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>오류 기록 — 잡사주</title>
<style>body{font-family:system-ui,sans-serif;max-width:1100px;margin:40px auto;padding:0 20px;background:#f6f5f9;color:#292237}h1{font-size:26px}input,button,select{padding:12px;border:1px solid #ccc;border-radius:8px}button{cursor:pointer;background:#493166;color:white}input{width:290px;max-width:90%}article{background:white;padding:20px;margin:14px 0;border-radius:12px;border:1px solid #e5e1ec}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}small{color:#686070}.controls{display:flex;gap:8px;flex-wrap:wrap}.error{color:#b52d39}</style>
<h1>화면·리포트 오류 기록</h1><p>최근 14일 기록입니다. 질문 내용, 이메일, 생년월일과 리포트 접근 토큰은 수집하지 않습니다.</p>
<form id="login" class="controls"><input id="key" type="password" autocomplete="off" aria-label="관리자 키" placeholder="관리자 키"><button>기록 불러오기</button></form>
<p><small>DIAGNOSTICS_ADMIN_KEY 또는 기존 COUPON_ADMIN_KEY를 사용합니다. 키는 이 화면을 닫으면 사라집니다.</small></p>
<div class="controls"><select id="filter" aria-label="상태 필터"><option value="error">오류만</option><option value="all">성공 포함</option></select><input id="search" aria-label="오류 확인 번호 검색" placeholder="오류 확인 번호 / 요청 번호"><button id="download">불러온 기록 내려받기</button></div>
<p id="status" role="status">관리자 키를 입력해 주세요.</p><div id="events"></div><button id="more" hidden>이전 기록 더 보기</button>
<script>
let records=[],cursor=null;
const byId=id=>document.getElementById(id);
function render(){const needle=byId('search').value.trim();const shown=records.filter(e=>(byId('filter').value==='all'||e.source==='browser'||e.outcome==='error')&&(!needle||e.id===needle||e.requestId===needle));byId('events').replaceChildren();for(const e of shown){const card=document.createElement('article');const title=document.createElement('strong');title.textContent=new Date(e.timestamp).toLocaleString('ko-KR')+' · '+(e.source==='browser'?'화면':'서버')+' · '+(e.code||e.stage)+' · '+(e.status||'');if(e.outcome==='error'||e.source==='browser')title.className='error';const details=document.createElement('pre');details.textContent=JSON.stringify(e,null,2);card.append(title,details);byId('events').append(card)}byId('status').textContent='불러온 '+records.length+'건 중 '+shown.length+'건 표시 · 저장 반영까지 잠시 걸릴 수 있습니다.';byId('more').hidden=!cursor}
async function load(more){byId('status').textContent='기록을 불러오는 중…';try{const res=await fetch('/api/admin/diagnostics'+(more&&cursor?'?cursor='+encodeURIComponent(cursor):''),{headers:{Authorization:'Bearer '+byId('key').value.trim()}});if(!res.ok)throw new Error(res.status===401?'관리자 키를 확인해 주세요.':'기록을 불러오지 못했습니다 ('+res.status+').');const data=await res.json();records=more?records.concat(data.events):data.events;cursor=data.cursor;render()}catch(e){byId('status').textContent=e.message}}
byId('login').onsubmit=e=>{e.preventDefault();load(false)};byId('more').onclick=()=>load(true);byId('filter').onchange=render;byId('search').oninput=render;byId('download').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(records,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='jobsaju-diagnostics.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
</script></html>`;
  return new Response(request.method === 'HEAD' ? null : html, { headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'X-Robots-Tag': 'noindex, nofollow', 'Referrer-Policy': 'no-referrer', 'X-Frame-Options': 'DENY' } });
}
